using Lurp.Shared;
using Lurp.Storage;

namespace Lurp.Tests;

/// <summary>
/// Phase 11 generated-code provenance proof: verifies that generated files are
/// correctly identified and cross-generated edges are marked.
/// </summary>
public sealed class GeneratedCodeProvenanceTests : InMemoryTestBase
{
    private const string HandWrittenDoc = "HandWritten.cs";
    private const string GeneratedDoc = "Widget.g.cs";

    private static IReadOnlyDictionary<string, string> TwoFiles(string handWritten, string generated)
        => new Dictionary<string, string>
        {
            [HandWrittenDoc] = handWritten,
            [GeneratedDoc] = generated
        };

    [Fact]
    public async Task GeneratedFile_MarksDeclarationsAndCrossGeneratedEdges()
    {
        var extraction = await ExtractAsync(TwoFiles("""
            namespace N;
            public class HandWritten
            {
                public void DoWork() { }
            }
            """, """
            // <auto-generated/>
            namespace N;
            public class Widget : HandWritten
            {
                public void Process() { DoWork(); }
            }
            """));

        var declarations = extraction.Result.Declarations;

        var handWrittenDecl = declarations.Single(d => d.SymbolId.FullyQualifiedName == "global::N.HandWritten");
        var widgetDecl = declarations.Single(d => d.SymbolId.FullyQualifiedName == "global::N.Widget");

        Assert.False(handWrittenDecl.IsGenerated, "Hand-written declarations should have IsGenerated == false");
        Assert.True(widgetDecl.IsGenerated, "Generated file declarations should have IsGenerated == true");

        var allEdges = extraction.Result.Edges;

        var inheritsEdge = extraction.SingleEdge("Inherits", "global::N.Widget", "global::N.HandWritten");
        Assert.True(inheritsEdge.IsCrossGenerated, "Inherits edge from generated file should have IsCrossGenerated == true");

        var handWrittenDeclaresDoWork = extraction.SingleEdge("Declares", "global::N.HandWritten", "global::N.HandWritten.DoWork");
        Assert.False(handWrittenDeclaresDoWork.IsCrossGenerated, "Declares edge from hand-written file should have IsCrossGenerated == false");

        var widgetDeclaresProcess = extraction.SingleEdge("Declares", "global::N.Widget", "global::N.Widget.Process");
        Assert.True(widgetDeclaresProcess.IsCrossGenerated, "Declares edge from generated file should have IsCrossGenerated == true");

        var callsEdge = extraction.SingleEdge("Calls", "global::N.Widget.Process", "global::N.HandWritten.DoWork");
        Assert.True(callsEdge.IsCrossGenerated, "Calls edge from generated file should have IsCrossGenerated == true");
    }
}