using Lurp.Adapters;
using Lurp.Shared;
using Lurp.Workspace;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.Data.Sqlite;
using System.Text;
using DocumentId = Lurp.Workspace.DocumentId;

namespace Lurp.Storage.Tests;

public partial class MigrationRunnerTests
{
    public class B4GeneratedCodeTests : IDisposable
    {
        private readonly string _dbPath;
        private SqliteIndexStore? _store;

        public B4GeneratedCodeTests()
        {
            _dbPath = Path.Combine(Path.GetTempPath(), $"indexer_b4_{Guid.NewGuid():N}.db");
        }

        public void Dispose()
        {
            _store?.Dispose();
            SqliteConnection.ClearAllPools();
            if (File.Exists(_dbPath))
                File.Delete(_dbPath);
        }

        private SqliteIndexStore CreateStore()
        {
            _store?.Dispose();
            var store = new SqliteIndexStore(_dbPath);
            store.Open();
            store.RunMigrations();
            _store = store;
            return store;
        }

        private static byte[] StringToBytes(string text) => Encoding.UTF8.GetBytes(text);

        private static void CreateSnapshotWithDocument(
            SqliteIndexStore store, string snapshotId, string relativePath, string content)
        {
            var lineStarts = "[0]";
            var sourceBytes = StringToBytes(content);

            var manifest = new SnapshotRow
            {
                SnapshotId = snapshotId,
                WorkspaceId = "workspace:///root/proj",
                GitRoot = "/root",
                SolutionPath = "/root/proj",
                SdkVersion = "10.0.301",
                CompilerVersion = "4.12.0.0",
                CreatedAtUtc = DateTime.UtcNow,
                Documents = new List<DocumentVersion>
                {
                    new DocumentVersion(sourceBytes) { DocumentId = "doc-" + relativePath, FilePath = relativePath, ContentHash = "hash1", Encoding = "utf-8", LineStart = lineStarts, CreatedAtUtc = DateTime.MinValue, LineStarts = lineStarts },
                }
            };
            store.SaveSnapshot(manifest);
        }

        [Fact]
        public void Migration008_RunTwice_IsIdempotent()
        {
            var runner = new MigrationRunner(_dbPath);

            runner.RunMigrations();
            Assert.Equal(VersionConstants.DatabaseSchemaVersion, runner.GetCurrentSchemaVersion());

            runner.RunMigrations();
            Assert.Equal(VersionConstants.DatabaseSchemaVersion, runner.GetCurrentSchemaVersion());

            using var connection = new SqliteConnection($"Data Source={_dbPath}");
            connection.Open();
            using var cmd = connection.CreateCommand();

            cmd.CommandText = "PRAGMA table_info(declarations);";
            using var reader = cmd.ExecuteReader();
            bool hasIsGenerated = false, hasGeneratorIdentity = false;
            while (reader.Read())
            {
                var colName = reader.GetString(1);
                if (colName == "is_generated") hasIsGenerated = true;
                if (colName == "generator_identity") hasGeneratorIdentity = true;
            }
            Assert.True(hasIsGenerated, "is_generated column should exist after migration 008");
            Assert.True(hasGeneratorIdentity, "generator_identity column should exist after migration 008");
        }

        [Fact]
        public void SaveDeclaration_WithIsGenerated_RoundTrips()
        {
            var store = CreateStore();
            var snapshotId = "snap-b4-rt-gen-001";
            CreateSnapshotWithDocument(store, snapshotId, "src/Generated.cs",
                "// <auto-generated>\nclass GeneratedClass { }");

            var decl = new SymbolDeclaration
            {
                SymbolId = new SymbolId("T:GeneratedClass", "asm1", "GeneratedClass"),
                Kind = IndexedSymbolKind.Type,
                DocumentVersionId = "doc-src/Generated.cs:hash1",
                FullSpan = new DeclarationSpan(0, 44),
                SignatureSpan = new DeclarationSpan(0, 26),
                BodySpan = new DeclarationSpan(26, 43),
                NameSpan = new DeclarationSpan(26, 40),
                IsGenerated = true,
                GeneratorIdentity = "SG/FooGenerator"
            };

            store.SaveDeclarations(snapshotId, [decl]);

            var info = store.GetSymbolInfo("T:GeneratedClass|asm1", snapshotId);
            Assert.NotNull(info);
            Assert.Equal("T:GeneratedClass", info!.SymbolId.DocCommentId);

            var sourceWithout = store.GetSymbolSource("T:GeneratedClass|asm1", snapshotId, ViewKind.Declaration);
            Assert.Null(sourceWithout);

            var sourceWith = store.GetSymbolSource("T:GeneratedClass|asm1", snapshotId, ViewKind.Declaration, includeGenerated: true);
            Assert.NotNull(sourceWith);
            Assert.Contains("GeneratedClass", sourceWith!);
        }

        [Fact]
        public void GetSymbolSource_ExcludesGeneratedByDefault()
        {
            var store = CreateStore();
            var snapshotId = "snap-b4-excl-001";
            CreateSnapshotWithDocument(store, snapshotId, "src/Gen.cs",
                "// <auto-generated>\nclass Gen { void Foo() { } }");

            var decl = new SymbolDeclaration
            {
                SymbolId = new SymbolId("T:Gen", "asm1", "Gen"),
                Kind = IndexedSymbolKind.Type,
                DocumentVersionId = "doc-src/Gen.cs:hash1",
                FullSpan = new DeclarationSpan(0, 40),
                SignatureSpan = new DeclarationSpan(0, 20),
                BodySpan = new DeclarationSpan(21, 39),
                NameSpan = new DeclarationSpan(18, 21),
                IsGenerated = true,
                GeneratorIdentity = "auto-generated-header"
            };

            store.SaveDeclarations(snapshotId, [decl]);

            var without = store.GetSymbolSource("T:Gen|asm1", snapshotId, ViewKind.Declaration);
            Assert.Null(without);

            var with = store.GetSymbolSource("T:Gen|asm1", snapshotId, ViewKind.Declaration, includeGenerated: true);
            Assert.NotNull(with);
        }

        [Fact]
        public void Search_ExcludesGeneratedByDefault()
        {
            var store = CreateStore();
            var snapshotId = "snap-b4-search-001";

            CreateSnapshotWithDocument(store, snapshotId, "src/Normal.cs",
                "class NormalClass { }");

            var normalDecl = new SymbolDeclaration
            {
                SymbolId = new SymbolId("T:NormalClass", "asm1", "NormalClass"),
                Kind = IndexedSymbolKind.Type,
                DocumentVersionId = "doc-src/Normal.cs:hash1",
                FullSpan = new DeclarationSpan(0, 20),
                SignatureSpan = new DeclarationSpan(0, 15),
                BodySpan = new DeclarationSpan(16, 19),
                NameSpan = new DeclarationSpan(7, 18),
                IsGenerated = false
            };

            var generatedDecl = new SymbolDeclaration
            {
                SymbolId = new SymbolId("T:GenClass", "asm1", "GenClass"),
                Kind = IndexedSymbolKind.Type,
                DocumentVersionId = "doc-src/Normal.cs:hash1",
                FullSpan = new DeclarationSpan(0, 20),
                SignatureSpan = new DeclarationSpan(0, 15),
                BodySpan = new DeclarationSpan(16, 19),
                NameSpan = new DeclarationSpan(7, 18),
                IsGenerated = true,
                GeneratorIdentity = "test-gen"
            };

            store.SaveDeclarations(snapshotId, [normalDecl, generatedDecl]);
            store.BuildSearchIndex(snapshotId);

            var normalResults = store.SearchSymbols("NormalClass", snapshotId);
            Assert.NotEmpty(normalResults);

            var withoutGen = store.SearchSymbols("GenClass", snapshotId);
            Assert.Empty(withoutGen);

            var withGen = store.SearchSymbols("GenClass", snapshotId, includeGenerated: true);
            Assert.NotEmpty(withGen);
        }

        [Fact]
        public void CrossGeneratedProvenanceMarker_AppendedForGeneratedEdges()
        {

            var compilation = CreateCompilation("class A { string M() => \"\"; }");
            var docVersions = CreateDocVersions("test.cs");

            var generatedDocs = new HashSet<DocumentId> { new("test.cs") };
            var extractor = new MemberEdgeExtractor(compilation, docVersions, generatedDocs, "snap-b4-provenance", "/");

            var edges = extractor.ExtractAll();

            var returns = edges.Where(e => e.Kind == "Returns").ToList();
            Assert.NotEmpty(returns);
            foreach (var edge in returns)
            {
                Assert.Equal(Provenance.CompilerProved, edge.Provenance);
                Assert.True(edge.IsCrossGenerated);
            }
        }

        private static Compilation CreateCompilation(string source, string path = "test.cs")
        {
            var syntaxTree = CSharpSyntaxTree.ParseText(source, path: path);
            return CSharpCompilation.Create(
                "TestAssembly",
                [syntaxTree],
                [MetadataReference.CreateFromFile(typeof(object).Assembly.Location)]);
        }

        private static IReadOnlyDictionary<DocumentId, DocumentVersionId> CreateDocVersions(string path)
        {
            return new Dictionary<DocumentId, DocumentVersionId>
            {
                { new DocumentId(path), DocumentVersionId.Compute("test-content") }
            };
        }
    }
}
