using System.Text.Json;
using Lurp.Handlers;
using Lurp.Storage;
using Lurp.Workspace;
using Xunit;

namespace Lurp.Tests;

/// <summary>
/// Audit §9 invariant T3 closes: lightweight modes now answer "where is X defined?"
/// with a locations array: document_path, start_line, end_line, is_generated.
/// </summary>
public sealed class SymbolLocationRetrievalTests : IntegrationTestBase
{
    private const string Project = "Core";
    private const string Document = "src/Core/Widget.cs";
    private const string PartialDocA = "src/Core/PartialA.cs";
    private const string PartialDocB = "src/Core/PartialB.cs";
    private const string GeneratedDoc = "src/Core/Generated.g.cs";
    private const string SymbolFqn = "global::Core.Widget";
    private const string PartialFqn = "global::Core.PartialType";
    private const string GeneratedFqn = "global::Core.GeneratedClass";

    // Ground truth (1-based physical lines). Declarations report their FullSpan:
    // a class preceded by a blank line starts on that blank line (leading trivia),
    // and end_line is the line the full_end offset lands on — the closing-brace
    // line for the last declaration in a file, or the following line when a
    // trailing newline separates it from more content.
    //
    // A partial type has one declaration row per *file* (the declarations table is
    // UNIQUE(symbol_id, document_version_id)), so PartialType lives in two files to
    // exercise the two-location case; two partials in one file would collapse to one.
    private const string WidgetSource = """
        namespace Core;

        public class Widget
        {
            public int Value { get; set; }

            public void DoWork()
            {
            }
        }
        """; // Widget: start_line 2 (blank line 2), end_line 10 (`}` line 10, last decl)

    private const string PartialASource = """
        namespace Core;

        public partial class PartialType
        {
            public void Method1() { }
        }
        """; // PartialType (PartialA.cs): start_line 2, end_line 6

    private const string PartialBSource = """
        namespace Core;

        public partial class PartialType
        {
            public void Method2() { }
        }
        """; // PartialType (PartialB.cs): start_line 2, end_line 6

    // A `.g.cs` file is recognized as generated by path, so its declarations carry
    // is_generated = true (the [GeneratedCode] attribute alone does not — Lurp keys
    // "generated" off the source document, not an attribute).
    private const string GeneratedSource = """
        // <auto-generated/>
        namespace Core;

        public class GeneratedClass
        {
            public void GeneratedMethod() { }
        }
        """; // GeneratedClass: start_line 3 (blank line 3), end_line 7 (`}` line 7, last decl)

    private async Task<string> SeedAndIndexAsync()
    {
        CreateProject(Project, new Dictionary<string, string>
        {
            ["Widget.cs"] = WidgetSource,
            ["PartialA.cs"] = PartialASource,
            ["PartialB.cs"] = PartialBSource,
            ["Generated.g.cs"] = GeneratedSource,
        });
        return await RunFullIndexAsync(DbPath);
    }

    private sealed record RunResult(string Stdout, CliExitException? Failure);

    /// <summary>Runs a handler in-process with stdout captured; a
    /// <see cref="CliExitException"/> (the only exit mechanism a handler uses) is
    /// returned in the result rather than thrown.</summary>
    private static RunResult RunCaptured(Action action)
    {
        var stdout = new StringWriter();
        var originalOut = Console.Out;
        CliExitException? failure = null;
        try
        {
            Console.SetOut(stdout);
            action();
        }
        catch (CliExitException ex)
        {
            failure = ex;
        }
        finally
        {
            Console.SetOut(originalOut);
        }
        return new RunResult(stdout.ToString(), failure);
    }

    [Fact]
    public async Task FindSymbol_ReturnsLocationsArray()
    {
        var snapshotId = await SeedAndIndexAsync();
        var widgetId = ResolveSymbolId(snapshotId, SymbolFqn);

        var result = RunCaptured(() => FindSymbolHandler.Run(new[]
        {
            "--mode=find-symbol",
            $"--symbol={widgetId}",
            $"--output-dir={TestDir}"
        }));

        Assert.Null(result.Failure);

        using var doc = JsonDocument.Parse(result.Stdout);
        var root = doc.RootElement;

        Assert.True(root.TryGetProperty("locations", out var locationsProp));
        Assert.True(locationsProp.ValueKind == JsonValueKind.Array);

        var locations = locationsProp.EnumerateArray().ToList();
        Assert.Single(locations);

        var loc = locations[0];
        Assert.Equal(Document, loc.GetProperty("document_path").GetString());
        Assert.Equal(2, loc.GetProperty("start_line").GetInt32()); // Widget FullSpan leading trivia = blank line 2
        Assert.Equal(10, loc.GetProperty("end_line").GetInt32()); // Widget's `}` is line 10 (last decl in file)
        Assert.False(loc.GetProperty("is_generated").GetBoolean());
    }

    [Fact]
    public async Task FindSymbol_PartialType_ReturnsAllLocations()
    {
        var snapshotId = await SeedAndIndexAsync();
        var partialId = ResolveSymbolId(snapshotId, PartialFqn);

        var result = RunCaptured(() => FindSymbolHandler.Run(new[]
        {
            "--mode=find-symbol",
            $"--symbol={partialId}",
            $"--output-dir={TestDir}"
        }));

        Assert.Null(result.Failure);

        using var doc = JsonDocument.Parse(result.Stdout);
        var root = doc.RootElement;

        Assert.True(root.TryGetProperty("locations", out var locationsProp));
        var locations = locationsProp.EnumerateArray().ToList();

        Assert.Equal(2, locations.Count);
        Assert.True(root.GetProperty("is_partial").GetBoolean());
        Assert.Equal(2, root.GetProperty("declaration_count").GetInt32());

        // Ordered by document_path: PartialA.cs before PartialB.cs.
        var loc1 = locations[0];
        Assert.Equal(PartialDocA, loc1.GetProperty("document_path").GetString());
        Assert.Equal(2, loc1.GetProperty("start_line").GetInt32()); // PartialA: blank line 2 leading trivia
        Assert.Equal(6, loc1.GetProperty("end_line").GetInt32()); // PartialA: `}` line 6 (last decl in file)
        Assert.False(loc1.GetProperty("is_generated").GetBoolean());

        var loc2 = locations[1];
        Assert.Equal(PartialDocB, loc2.GetProperty("document_path").GetString());
        Assert.Equal(2, loc2.GetProperty("start_line").GetInt32()); // PartialB: blank line 2 leading trivia
        Assert.Equal(6, loc2.GetProperty("end_line").GetInt32()); // PartialB: `}` line 6 (last decl in file)
        Assert.False(loc2.GetProperty("is_generated").GetBoolean());
    }

    [Fact]
    public async Task FindSymbol_WithIncludeGenerated_ReturnsGeneratedLocations()
    {
        var snapshotId = await SeedAndIndexAsync();
        var generatedId = ResolveSymbolId(snapshotId, GeneratedFqn);

        var result = RunCaptured(() => FindSymbolHandler.Run(new[]
        {
            "--mode=find-symbol",
            $"--symbol={generatedId}",
            $"--output-dir={TestDir}",
            "--include-generated"
        }));

        Assert.Null(result.Failure);

        using var doc = JsonDocument.Parse(result.Stdout);
        var root = doc.RootElement;

        Assert.True(root.TryGetProperty("locations", out var locationsProp));
        var locations = locationsProp.EnumerateArray().ToList();

        Assert.Single(locations);
        var loc = locations[0];
        Assert.Equal(GeneratedDoc, loc.GetProperty("document_path").GetString());
        Assert.Equal(3, loc.GetProperty("start_line").GetInt32()); // GeneratedClass: blank line 3 leading trivia
        Assert.Equal(7, loc.GetProperty("end_line").GetInt32()); // GeneratedClass: `}` line 7 (last decl in file)
        Assert.True(loc.GetProperty("is_generated").GetBoolean());
    }

    [Fact]
    public async Task GetSymbolMetadata_ReturnsLocationsArray()
    {
        var snapshotId = await SeedAndIndexAsync();
        var widgetId = ResolveSymbolId(snapshotId, SymbolFqn);

        var result = RunCaptured(() => GetSymbolHandler.Run(new[]
        {
            "--mode=get-symbol",
            $"--symbol={widgetId}",
            $"--view=metadata",
            $"--output-dir={TestDir}"
        }));

        Assert.Null(result.Failure);

        using var doc = JsonDocument.Parse(result.Stdout);
        var root = doc.RootElement;

        Assert.True(root.TryGetProperty("locations", out var locationsProp));
        Assert.True(locationsProp.ValueKind == JsonValueKind.Array);

        var locations = locationsProp.EnumerateArray().ToList();
        Assert.Single(locations);

        var loc = locations[0];
        Assert.Equal(Document, loc.GetProperty("document_path").GetString());
        Assert.Equal(2, loc.GetProperty("start_line").GetInt32()); // Widget FullSpan leading trivia = blank line 2
        Assert.Equal(10, loc.GetProperty("end_line").GetInt32()); // Widget's `}` is line 10 (last decl in file)
        Assert.False(loc.GetProperty("is_generated").GetBoolean());
    }

    [Fact]
    public async Task Navigate_ReturnsLineNumbers()
    {
        var snapshotId = await SeedAndIndexAsync();
        var widgetId = ResolveSymbolId(snapshotId, SymbolFqn);

        using var store = OpenStore(DbPath);
        var loc = Assert.Single(store.GetDeclarationLocations(widgetId, snapshotId));
        var lineToNavigate = loc.StartLine;

        var result = RunCaptured(() => NavigateHandler.Run(new[]
        {
            "--mode=navigate",
            $"--file={Document}",
            $"--line={lineToNavigate}",
            $"--output-dir={TestDir}"
        }));

        Assert.Null(result.Failure);

        using var doc = JsonDocument.Parse(result.Stdout);
        var root = doc.RootElement;
        var target = root.GetProperty("target");

        Assert.Equal(lineToNavigate, target.GetProperty("start_line").GetInt32());
        Assert.Equal(loc.EndLine, target.GetProperty("end_line").GetInt32());
        Assert.Equal(Document, target.GetProperty("document_path").GetString());
    }

    [Fact]
    public async Task Navigate_RoundTrip_ThroughLine_ReturnsSameSymbol()
    {
        var snapshotId = await SeedAndIndexAsync();
        var widgetId = ResolveSymbolId(snapshotId, SymbolFqn);

        string reportedStartLine;
        using (var store = OpenStore(DbPath))
        {
            var loc = Assert.Single(store.GetDeclarationLocations(widgetId, snapshotId));
            reportedStartLine = loc.StartLine.ToString(System.Globalization.CultureInfo.InvariantCulture);
        }

        var result = RunCaptured(() => NavigateHandler.Run(new[]
        {
            "--mode=navigate",
            $"--file={Document}",
            $"--line={reportedStartLine}",
            $"--output-dir={TestDir}"
        }));

        Assert.Null(result.Failure);

        using var doc = JsonDocument.Parse(result.Stdout);
        var target = doc.RootElement.GetProperty("target");
        Assert.Equal(widgetId, target.GetProperty("symbol_id").GetString());
        Assert.Equal(Document, target.GetProperty("document_path").GetString());
    }
}