using Lurp.Storage;
using Lurp.Workspace;
using Microsoft.Build.Locator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;
using DocumentId = Lurp.Workspace.DocumentId;
using RoslynDocumentId = Microsoft.CodeAnalysis.DocumentId;

namespace Lurp.Tests;

/// <summary>
///     Regression coverage for the unhandled UTF-8 decode crash reported against
///     <c>--mode=index</c>: <see cref="WorkspaceInfo.IsGeneratedHeader" /> threw when a
///     multi-byte character straddled its 512-byte header-sniff cutoff, and
///     <see cref="WorkspaceInfo" />'s content decode threw outright on any file that
///     wasn't valid UTF-8/UTF-16 text (binary content, a truncated multi-byte
///     sequence, or a different encoding entirely), killing the whole index run.
///     Both are now non-fatal: the header sniff decodes leniently, and a document
///     that isn't valid text is skipped (with a warning) rather than crashing.
/// </summary>
public sealed class WorkspaceInfoDecodeTests : IDisposable
{
    private readonly string _tempDir;

    public WorkspaceInfoDecodeTests()
    {
        _tempDir = Path.Combine(Path.GetTempPath(), $"lurp-decode-{Guid.NewGuid():N}");
        Directory.CreateDirectory(_tempDir);
    }

    public void Dispose()
    {
        try
        {
            if (Directory.Exists(_tempDir))
                Directory.Delete(_tempDir, true);
        }
        catch
        {
        }

        GC.SuppressFinalize(this);
    }

    /// <summary>
    ///     Builds an <see cref="AdhocWorkspace" /> project whose documents point at real
    ///     files written to disk with the given raw bytes, then constructs
    ///     <see cref="WorkspaceInfo" /> from it exactly as <see cref="WorkspaceLoader" />
    ///     would. No .csproj/MSBuild involved: <see cref="WorkspaceInfo" /> re-reads bytes
    ///     from <c>document.FilePath</c>, so the placeholder in-memory <see cref="SourceText" />
    ///     never matters.
    /// </summary>
    private (WorkspaceInfo Info, RecordingOutputSink Sink) BuildWorkspaceInfo(IReadOnlyDictionary<string, byte[]> rawFiles)
    {
        using var workspace = new AdhocWorkspace();
        var projectId = ProjectId.CreateNewId();
        var solutionId = SolutionId.CreateNewId();

        workspace.AddSolution(SolutionInfo.Create(
            solutionId, VersionStamp.Create(), Path.Combine(_tempDir, "Test.slnx")));

        var solution = workspace.CurrentSolution
            .AddProject(ProjectInfo.Create(
                projectId, VersionStamp.Create(), "TestProject", "TestProject", LanguageNames.CSharp));

        foreach (var (fileName, bytes) in rawFiles)
        {
            var fullPath = Path.Combine(_tempDir, fileName);
            Directory.CreateDirectory(Path.GetDirectoryName(fullPath)!);
            File.WriteAllBytes(fullPath, bytes);
            solution = solution.AddDocument(
                RoslynDocumentId.CreateNewId(projectId),
                fileName,
                SourceText.From(""),
                filePath: fullPath);
        }

        workspace.TryApplyChanges(solution);

        var sink = new RecordingOutputSink();
        var info = new WorkspaceInfo(workspace.CurrentSolution, _tempDir, sink);
        return (info, sink);
    }

    // --- 1. The reported crash: a valid UTF-8 file with a character straddling byte 512 ---

    [Fact]
    public void HeaderStraddle_ValidUtf8File_DoesNotThrow_AndRoundTrips()
    {
        const int prefixLength = 511;
        var content = new string('x', prefixLength) + "é\n// end of straddling file\n";
        var contentBytes = Encoding.UTF8.GetBytes(content);

        // Sanity-check the fixture: byte 511 is the lead byte of "é" (0xC3) and its
        // continuation byte (0xA9) lands at byte 512 — one past IsGeneratedHeader's
        // 512-byte cutoff. This is exactly what reproduced the reporter's stack trace.
        Assert.Equal(0xC3, contentBytes[511]);
        Assert.Equal(0xA9, contentBytes[512]);

        var (info, _) = BuildWorkspaceInfo(new Dictionary<string, byte[]> { ["Straddle.cs"] = contentBytes });

        var docId = new DocumentId("Straddle.cs");
        Assert.True(info.Documents.ContainsKey(docId));
        Assert.Equal(contentBytes, info.DocumentContents[docId].Content);
        Assert.False(info.GeneratedDocuments.Contains(docId));
    }

    // --- 2. The straddle must not corrupt generated-file detection ---

    [Fact]
    public void HeaderStraddle_WithAutoGeneratedMarker_StillDetectedAsGenerated()
    {
        const string marker = "// <auto-generated>\n";
        var padLength = 511 - Encoding.UTF8.GetByteCount(marker);
        var content = marker + new string('x', padLength) + "é\n// end\n";
        var contentBytes = Encoding.UTF8.GetBytes(content);

        Assert.Equal(0xC3, contentBytes[511]);
        Assert.Equal(0xA9, contentBytes[512]);

        var (info, _) = BuildWorkspaceInfo(new Dictionary<string, byte[]> { ["Marked.cs"] = contentBytes });

        var docId = new DocumentId("Marked.cs");
        Assert.True(info.Documents.ContainsKey(docId));
        Assert.True(info.GeneratedDocuments.Contains(docId));
    }

    // --- 3. Generated-header detection is otherwise unaffected by the lenient decode ---

    [Theory]
    [InlineData("// <auto-generated>\nnamespace N;\n", true)]
    [InlineData("[GeneratedCode(\"tool\", \"1.0\")]\nnamespace N;\n", true)]
    [InlineData("namespace N;\npublic class Plain { }\n", false)]
    public void GeneratedHeaderDetection_StillCorrect_ForShortFiles(string content, bool expectedGenerated)
    {
        var (info, _) = BuildWorkspaceInfo(new Dictionary<string, byte[]> { ["Doc.cs"] = Encoding.UTF8.GetBytes(content) });

        Assert.Equal(expectedGenerated, info.GeneratedDocuments.Contains(new DocumentId("Doc.cs")));
    }

    // --- 4. A genuinely invalid-UTF-8 source file is skipped, not fatal ---

    [Fact]
    public void InvalidUtf8Source_IsSkipped_IndexingCompletes()
    {
        var before = Encoding.UTF8.GetBytes("// comment with e-acute: ");
        var invalidTail = new byte[] { 0xE9, 0x20 }; // 0xE9 starts a 3-byte sequence; 0x20 isn't a continuation byte.
        var after = Encoding.UTF8.GetBytes("end\n");
        var invalidBytes = before.Concat(invalidTail).Concat(after).ToArray();

        var (info, sink) = BuildWorkspaceInfo(new Dictionary<string, byte[]>
        {
            ["Latin1.cs"] = invalidBytes,
            ["Sibling.cs"] = Encoding.UTF8.GetBytes("namespace N;\npublic class Sibling { }\n")
        });

        var invalidId = new DocumentId("Latin1.cs");
        var siblingId = new DocumentId("Sibling.cs");

        Assert.False(info.Documents.ContainsKey(invalidId));
        Assert.False(info.DocumentContents.ContainsKey(invalidId));
        Assert.False(info.GeneratedDocuments.Contains(invalidId));

        Assert.True(info.Documents.ContainsKey(siblingId));
        Assert.True(info.DocumentContents.ContainsKey(siblingId));

        Assert.Contains(sink.ErrorLines, l => l.Contains("Latin1.cs"));
    }

    // --- 5. Outright binary content (the reporter's original theory) is skipped, not fatal ---

    [Fact]
    public void BinaryContent_IsSkipped_IndexingCompletes()
    {
        var pngBytes = new byte[] { 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x01, 0x02, 0xFF, 0xFE, 0xFD };

        var (info, sink) = BuildWorkspaceInfo(new Dictionary<string, byte[]>
        {
            ["logo.png"] = pngBytes,
            ["Sibling.cs"] = Encoding.UTF8.GetBytes("namespace N;\npublic class Sibling { }\n")
        });

        var pngId = new DocumentId("logo.png");
        var siblingId = new DocumentId("Sibling.cs");

        Assert.False(info.Documents.ContainsKey(pngId));
        Assert.True(info.Documents.ContainsKey(siblingId));
        Assert.Contains(sink.ErrorLines, l => l.Contains("logo.png"));
    }

    // --- 6. BOM handling is unchanged: all three BOM'd forms normalize identically ---

    [Fact]
    public void BomVariants_NormalizeToIdenticalContentAndHash_AsPlainUtf8()
    {
        const string text = "namespace N;\npublic class Widget { }\n";
        var plainBytes = Encoding.UTF8.GetBytes(text);
        var utf8BomBytes = new byte[] { 0xEF, 0xBB, 0xBF }.Concat(plainBytes).ToArray();
        var utf16LeBytes = new byte[] { 0xFF, 0xFE }.Concat(Encoding.Unicode.GetBytes(text)).ToArray();
        var utf16BeBytes = new byte[] { 0xFE, 0xFF }.Concat(Encoding.BigEndianUnicode.GetBytes(text)).ToArray();

        var (info, _) = BuildWorkspaceInfo(new Dictionary<string, byte[]>
        {
            ["Plain.cs"] = plainBytes,
            ["Utf8Bom.cs"] = utf8BomBytes,
            ["Utf16Le.cs"] = utf16LeBytes,
            ["Utf16Be.cs"] = utf16BeBytes
        });

        var plainId = new DocumentId("Plain.cs");
        var utf8BomId = new DocumentId("Utf8Bom.cs");
        var utf16LeId = new DocumentId("Utf16Le.cs");
        var utf16BeId = new DocumentId("Utf16Be.cs");

        Assert.Equal(plainBytes, info.DocumentContents[plainId].Content);
        Assert.Equal(plainBytes, info.DocumentContents[utf8BomId].Content);
        Assert.Equal(plainBytes, info.DocumentContents[utf16LeId].Content);
        Assert.Equal(plainBytes, info.DocumentContents[utf16BeId].Content);

        var plainHash = info.Documents[plainId].Hash;
        Assert.Equal(plainHash, info.Documents[utf8BomId].Hash);
        Assert.Equal(plainHash, info.Documents[utf16LeId].Hash);
        Assert.Equal(plainHash, info.Documents[utf16BeId].Hash);
    }

    // --- 7. A truncated multi-byte sequence is skipped, not fatal ---

    [Fact]
    public void TruncatedUtf16_IsSkipped_NotFatal()
    {
        // FF FE BOM + 'A' (0x41 0x00) + one trailing odd byte: an incomplete UTF-16 code unit.
        var truncated = new byte[] { 0xFF, 0xFE, 0x41, 0x00, 0x42 };

        var (info, sink) = BuildWorkspaceInfo(new Dictionary<string, byte[]>
        {
            ["Truncated.cs"] = truncated,
            ["Sibling.cs"] = Encoding.UTF8.GetBytes("namespace N;\npublic class Sibling { }\n")
        });

        var truncatedId = new DocumentId("Truncated.cs");
        var siblingId = new DocumentId("Sibling.cs");

        Assert.False(info.Documents.ContainsKey(truncatedId));
        Assert.False(info.DocumentContents.ContainsKey(truncatedId));
        Assert.True(info.Documents.ContainsKey(siblingId));
        Assert.Contains(sink.ErrorLines, l => l.Contains("Truncated.cs"));
    }

    // --- 8. A file that goes from source to binary since it was indexed reads as stale ---

    [SkippableFact]
    public async Task Freshness_FileGoneInvalidSinceIndexing_IsStale_NotFatal()
    {
        Skip.If(!MSBuildLocator.IsRegistered && !IntegrationHarness.TryRegisterMSBuild(),
            "MSBuild is not available on this system. Cannot run integration test.");

        var projDir = Path.Combine(_tempDir, "src", "TestProject");
        Directory.CreateDirectory(projDir);
        File.WriteAllText(Path.Combine(projDir, "TestProject.csproj"), """
                                                                        <Project Sdk="Microsoft.NET.Sdk">
                                                                          <PropertyGroup>
                                                                            <TargetFramework>net10.0</TargetFramework>
                                                                          </PropertyGroup>
                                                                        </Project>
                                                                        """);

        var srcPath = Path.Combine(projDir, "Sample.cs");
        File.WriteAllText(srcPath, "namespace N;\npublic class Sample { }\n");

        var solutionPath = Path.Combine(_tempDir, "Test.slnx");
        File.WriteAllText(solutionPath, """
                                         <Solution>
                                           <Folder Name="/src/">
                                             <Project Path="src/TestProject/TestProject.csproj" />
                                           </Folder>
                                         </Solution>
                                         """);

        var dbPath = Path.Combine(_tempDir, "index.db");
        var snapshotId = await IntegrationHarness.RunFullIndexAsync(dbPath, solutionPath);

        // Corrupt the indexed file with invalid UTF-8 and force a strictly-later
        // mtime so the cheap stat check treats it as touched.
        File.WriteAllBytes(srcPath, [0x6E, 0x61, 0x6D, 0x65, 0xE9, 0x20]);
        File.SetLastWriteTimeUtc(srcPath, DateTime.UtcNow.AddMinutes(5));

        using var store = IntegrationHarness.OpenReadStore(dbPath);
        var stamp = WorkspaceFreshness.CheckFreshnessCheap(store, store, snapshotId, FreshnessMode.Hash);

        Assert.Equal("stale", stamp.State);
        Assert.Contains(stamp.ChangedDocumentsSample, p => p.Contains("Sample.cs"));
    }

    // --- 9. End-to-end: the reporter's headline symptom (no snapshot produced) is fixed ---

    [SkippableFact]
    public async Task FullIndex_WithBinaryPulledIntoCompileGlob_ProducesSnapshot()
    {
        Skip.If(!MSBuildLocator.IsRegistered && !IntegrationHarness.TryRegisterMSBuild(),
            "MSBuild is not available on this system. Cannot run integration test.");

        var projDir = Path.Combine(_tempDir, "src", "TestProject");
        var wwwrootDir = Path.Combine(projDir, "wwwroot");
        Directory.CreateDirectory(wwwrootDir);

        // Broadens the Compile glob so a binary asset lands in project.Documents,
        // reproducing the only route (see investigation notes) by which a binary
        // file can reach WorkspaceInfo.BuildDocumentMap in a real solution.
        File.WriteAllText(Path.Combine(projDir, "TestProject.csproj"), """
                                                                        <Project Sdk="Microsoft.NET.Sdk">
                                                                          <PropertyGroup>
                                                                            <TargetFramework>net10.0</TargetFramework>
                                                                          </PropertyGroup>
                                                                          <ItemGroup>
                                                                            <Compile Include="wwwroot\**\*" />
                                                                          </ItemGroup>
                                                                        </Project>
                                                                        """);

        File.WriteAllText(Path.Combine(projDir, "Sample.cs"), "namespace N;\npublic class Sample { }\n");
        File.WriteAllBytes(Path.Combine(wwwrootDir, "logo.png"),
            [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x01, 0x02, 0x03]);

        var solutionPath = Path.Combine(_tempDir, "Test.slnx");
        File.WriteAllText(solutionPath, """
                                         <Solution>
                                           <Folder Name="/src/">
                                             <Project Path="src/TestProject/TestProject.csproj" />
                                           </Folder>
                                         </Solution>
                                         """);

        var dbPath = Path.Combine(_tempDir, "index.db");

        var snapshotId = await IntegrationHarness.RunFullIndexAsync(dbPath, solutionPath);
        Assert.False(string.IsNullOrWhiteSpace(snapshotId));

        using var store = IntegrationHarness.OpenReadStore(dbPath);
        var manifest = store.LoadLatestSnapshot();
        Assert.NotNull(manifest);
        Assert.Equal(snapshotId, manifest!.SnapshotId);
    }

    private sealed class RecordingOutputSink : IOutputSink
    {
        public List<string> ErrorLines { get; } = [];

        public void Write(string message)
        {
        }

        public void WriteLine(string message = "")
        {
        }

        public void WriteErrorLine(string message = "")
        {
            ErrorLines.Add(message);
        }
    }
}
